services:
  backend:
    image: kontulari-backend 
    container_name: kontulari-backend
    restart: always
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    env_file:
      - api/.env
    ports:
      - 8080:8080
  
  frontend:
    image: kontulari-frontend
    container_name: kontulari-frontend
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./app/src/app:/app/src/app
    env_file:
      - app/.env
    ports:
      - 3000:3000

    